import {
  type LightbulbIcon as LucideProps,
  AlertCircle,
  ArrowUpDown,
  BarChart,
  BarChart4,
  Book,
  BookOpen,
  Box,
  Calculator,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  Clock,
  ClipboardCheck,
  Coins,
  DollarSign,
  FileCheck,
  FileText,
  FileWarning,
  Github,
  Hammer,
  HeartHandshake,
  Home,
  Info,
  Moon,
  Percent,
  Plus,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  SunMedium,
  TrendingUp,
  Twitter,
  User,
  Users,
  X,
  type LucideIcon,
} from "lucide-react"
import Image from "next/image"

export type Icon = LucideIcon

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  twitter: Twitter,
  gitHub: Github,
  check: Check,
  x: X,
  user: User,
  users: Users,
  dollar: DollarSign,
  barChart: BarChart,
  trendingUp: TrendingUp,
  arrowUpDown: ArrowUpDown,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  calculator: Calculator,
  clipboardCheck: ClipboardCheck,
  fileCheck: FileCheck,
  fileWarning: FileWarning,
  fileText: FileText,
  shield: Shield,
  coins: Coins,
  info: Info,
  home: Home,
  box: Box,
  hammer: Hammer,
  shoppingBag: ShoppingBag,
  heartHandshake: HeartHandshake,
  book: Book,
  bookOpen: BookOpen,
  calendar: Calendar,
  clock: Clock,
  percent: Percent,
  barChart4: BarChart4,
  chevronDown: ChevronDown,
  plus: Plus,
  search: Search,
  settings: Settings,
  
}

